name: MHDF-Tools
version: '${project.version}'
main: cn.ChengZhiYa.MHDFTools.MHDFTools
api-version: '1.17'
authoendrs: [ ChengZhiYa, Dg32z_ ]
softdepend: [ Vault, PlaceholderAPI, ProtocolLib ]
description: qwq
permissions:
  MHDFTools.Command.Back:
    default: true
  MHDFTools.Command.Day:
    default: true
  MHDFTools.Command.DelHome:
    default: true
  MHDFTools.Command.Fly:
    default: op
  MHDFTools.Command.Fly.Infinite:
    default: op
  MHDFTools.Command.Fly.Give:
    default: op
  MHDFTools.Command.FlyTime:
    default: op
  MHDFTools.Command.Gamemode:
    default: op
  MHDFTools.Command.Hat:
    default: true
  MHDFTools.Command.Home:
    default: true
  MHDFTools.Command.Invsee:
    default: op
  MHDFTools.Command.Ip:
    default: op
  MHDFTools.Command.List:
    default: op
  MHDFTools.Command.Login:
    default: true
  MHDFTools.Command.MHDFTools:
    default: op
  MHDFTools.Command.Money:
    default: true
  MHDFTools.Command.MoneyAdmin:
    default: op
  MHDFTools.Command.Night:
    default: op
  MHDFTools.Command.Pay:
    default: true
  MHDFTools.Command.Register:
    default: true
  MHDFTools.Command.SetHome:
    default: true
  MHDFTools.Command.SetSpawn:
    default: op
  MHDFTools.Command.Spawn:
    default: true
  MHDFTools.Command.Stop:
    default: op
  MHDFTools.Command.Sun:
    default: op
  MHDFTools.Command.Tpa:
    default: true
  MHDFTools.Command.TpBack:
    default: true
  MHDFTools.Command.Trash:
    default: true
  MHDFTools.Command.TpaHere:
    default: true
  MHDFTools.Command.UnBack:
    default: true
  MHDFTools.Command.Vanish:
    default: op
  MHDFTools.Command.Rotate:
    default: op
  MHDFTools.Command.Version:
    default: op
  MHDFTools.FastUse.EnderChest:
    default: true
  MHDFTools.FastUse.ShulkerBox:
    default: true
  MHDFTools.FastUse.CraftingTable:
    default: true
  MHDFTools.SendUpdateMessage:
    default: op
  MHDFTools.JoinMessage:
    default: true
  MHDFTools.QuitMessage:
    default: true
